<?php
/**
 * MailCampaigns Connector
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Magento extension
 * @package    MailCampaigns
 * @copyright  Copyright (c) 2016 MailCampaigns. (http://www.mailcampaigns.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php

$objectManager 	                            = \Magento\Framework\App\ObjectManager::getInstance();
$helper                                     = $objectManager->get('\MailCampaigns\Connector\Helper\Data');
//$helper 									= $this->helper('MailCampaigns\Connector\Helper\Data');

$mailcampaigns_tracking_code_order_success 	= $helper->getScopeConfig('mailcampaignstracking/general/tracking_code_order_success');

$api_key 		= $helper->getScopeConfig('mailcampaignsapi/general/api_key');
$session 		= $objectManager->create('\Magento\Customer\Model\Session')->getData();
$customer_id	= $objectManager->create('\Magento\Customer\Model\Customer')->getCustomerId();

if ($mailcampaigns_tracking_code_order_success == 1 )
{	
	$session 			= $objectManager->create('\Magento\Checkout\Model\Session')->getData();
	$last_real_order_id = $objectManager->create('\Magento\Checkout\Model\Session')->getLastRealOrderId();
	$order_data 			= $objectManager->create('\Magento\Sales\Model\Order')->loadByIncrementId($last_real_order_id)->getData();
	
	$order_id 		= $order_data["entity_id"];
	$quote_id 		= $order_data["quote_id"];
	$store_id		= $order_data["store_id"];
	$customer_id	= $order_data["customer_id"];

	if ($order_id > 0)
	{
		// build post data
		$postdata = array(
			'store_id' => $store_id,
			'customer_id' => $customer_id,
			'visitor_id' => 0,
			'quote_id' => $quote_id,
			'order_id' => $order_id
		);
		
		// call tracking javascript code
		print '<script type="text/javascript" src="//interface.mailcampaigns.nl/w/'.$api_key.'/'.base64_encode(json_encode($postdata)).'"></script>';	
	}
}