<?php

use Magento\Customer\Model\Session;
use Magento\Framework\App\ObjectManager;
use Magento\Sales\Model\Order;
use MailCampaigns\Magento2Connector\Helper\ConfigLoader;

$objectManager = ObjectManager::getInstance();

// Get configuration.
$helper = $objectManager->get(ConfigLoader::class);
$trackingCodeEnabled = $helper->getScopeConfig('mailcampaigns_tracking/general/tracking_code_order_success');
$apiKey = $helper->getScopeConfig('mailcampaigns_api/general/api_key');

// Get session.
$session = $objectManager->create(Session::class);

if ($trackingCodeEnabled) {
    $order = $objectManager->create(Order::class);
    $orderData = $order->loadByIncrementId($session->getLastRealOrderId())->getData();
    $orderId = $orderData['entity_id'];

    if ($orderId > 0) {
        // Build post data.
        $postData = [
            'store_id' => $orderData['store_id'],
            'customer_id' => $orderData['customer_id'],
            'visitor_id' => 0,
            'quote_id' => $orderData['quote_id'],
            'order_id' => $orderId
        ];

        /** @codingStandardsIgnoreStart */
        print '
        <script type=\'text/javascript\'>
            (function(d,t) {
            _mctc = {\'onload\': function() { this.mctrkDocumentLoad(); }};
            var s=d.getElementsByTagName(t)[0], js=d.createElement(t); js.async=1;
            js.src=\'https://interface.mailcampaigns.nl/w/' . $apiKey . '/' . base64_encode(json_encode($postData)) . '\';
            s.parentNode.insertBefore(js,s);
            })(document,\'script\');
        </script>
        ';
        /** @codingStandardsIgnoreEnd */
    }
}
