<?php

use Magento\Customer\Model\Session;
use Magento\Framework\App\Config;
use Magento\Framework\App\ObjectManager;
use Magento\Sales\Model\Order;
use Magento\Store\Model\ScopeInterface;

$objectManager = ObjectManager::getInstance();

/** @var Config $config */
$config = $objectManager->get(Config::class);

// Get configuration.
$trackingCodeEnabled = $config->getValue('mailcampaigns_tracking/general/tracking_code_order_success',
        ScopeInterface::SCOPE_STORE) === '1';
$apiKey = $config->getValue('mailcampaigns_api/general/api_key', ScopeInterface::SCOPE_STORE);

// Get session.
$session = $objectManager->create(Session::class);

if ($trackingCodeEnabled) {
    $order = $objectManager->create(Order::class);
    $orderData = $order->loadByIncrementId($session->getLastRealOrderId())->getData();
    $orderId = isset($orderData['entity_id']) ? (int)$orderData['entity_id'] : 0;

    if ($orderId > 0) {
        // Build post data.
        $postData = [
            'store_id' => $orderData['store_id'],
            'customer_id' => $orderData['customer_id'],
            'visitor_id' => 0,
            'quote_id' => $orderData['quote_id'],
            'order_id' => $orderId
        ];

        /** @codingStandardsIgnoreStart */
        print '
<script>
    (function (d, t) {
        _mctc = {
            "onload": function () {
                this.mctrkDocumentLoad();
            }
        };

        var s = d.getElementsByTagName(t)[0], js = d.createElement(t);

        js.async = 1;
        js.src = "https://interface.mailcampaigns.nl/w/' . $apiKey . '/' . base64_encode(json_encode($postData)) . '";
        s.parentNode.insertBefore(js, s);
    })(document, "script");
</script>
';
        /** @codingStandardsIgnoreEnd */
    }
}
