<?php /** @noinspection PhpDeprecationInspection */

use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Customer\Model\Customer;
use Magento\Framework\App\Config;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Registry;
use Magento\Store\Model\ScopeInterface;

$objectManager = ObjectManager::getInstance();

/** @var Config $config */
$config = $objectManager->get(Config::class);

// Get configuration.
$trackingCodeEnabled = $config->getValue('mailcampaigns_tracking/general/tracking_code',
        ScopeInterface::SCOPE_STORE) === '1';
$apiKey = $config->getValue('mailcampaigns_api/general/api_key', ScopeInterface::SCOPE_STORE);

if ($trackingCodeEnabled) {
    $customer = $objectManager->create(Customer::class);
    $storeId = 0;
    $customerId = 0;
    $productId = 0;

    if ($customer->getId() > 0) {
        $storeId = $customer->getStoreId();
        $customerId = $customer->getId();
    }

    $product = $objectManager->get(Registry::class)->registry('current_product');

    if ($product instanceof ProductInterface) {
        $productId = $product->getId();
    }

    // Build post data.
    $postData = [
        'store_id' => (int)$storeId,
        'customer_id' => (int)$customerId,
        'visitor_id' => 0,
        'product_id' => (int)$productId
    ];

    // Create cookie expiration datetime string (~ a year).
    $cookieExpires = date('M d Y H:i:s', time() + 365 * 24 * 60 * 60);

    /** @codingStandardsIgnoreStart */
    print '
	<script type=\'text/javascript\'>
        (function(d,t) {
        _mctc = {\'onload\': function() { this.mctrkDocumentLoad(); }};
        var s=d.getElementsByTagName(t)[0], js=d.createElement(t); js.async=1;
        js.src=\'https://interface.mailcampaigns.nl/w/' . $apiKey . '/' . base64_encode(json_encode($postData)) . '\';
        s.parentNode.insertBefore(js,s);
        if (typeof mc_session_id !== "undefined") { document.cookie = "mc_session_id=" + mc_session_id + "; expires=' . $cookieExpires . '; path=/"; }
        if (typeof mc_subscriber_id !== "undefined") {  document.cookie = "mc_subscriber_id=" + mc_subscriber_id + "; expires=' . $cookieExpires . '; path=/"; }
        if (typeof mc_subscriber_email !== "undefined") { document.cookie = "mc_subscriber_email=" + mc_subscriber_email + "; expires=' . $cookieExpires . '; path=/"; }
        })(document,\'script\');
	</script>
	';
    /** @codingStandardsIgnoreEnd */
}
