<?php

use MailCampaigns\Magento2Connector\Block\Adminhtml\System\Config\ModuleVersion;

/**
 * @var $block ModuleVersion
 */
?>

<!-- MailCampaigns Magento2Connector Module Version -->
<div><?= /* @noEscape */ $block->getModuleVersion() ?></div>
<!--/ MailCampaigns Magento2Connector Module Version -->

<script>
    require([
        'jquery'
    ], function ($) {
        $(function () {
            console.debug('Loaded MailCampaigns Javascript.');

            // Define selectors.
            const selNotification = '#mailcampaigns_api_info .comment';
            const selStoreSwitcher = '#store_switcher';

            /*
            ################################
            ##     Scope notification     ##
            ################################
            */

            // Is the current page a store view?
            let isStoreView = $(selStoreSwitcher).val() === '1';

            // Show scope notification when not currently in store view.
            if (!isStoreView) {
                $(selNotification).show().find('span').show();
            } else {
                $('#row_mailcampaigns_api_info_module_version td').css('padding-top', 0);
            }
        });
    });
</script>
